# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         warnings-DynamicScope
version:      1.02
version_from: lib/warnings/DynamicScope.pm
installdirs:  site
requires:
    Symbol::Values:                1.05
    Test::Exception:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
